### ISSUE TITLE
great idea

### ISSUE THREAD

**Issue by kernelschmelze** [MarinX/agewasm#1]
I like the idea. Maybe a good opportunity to make Age accessible to less technically savvy people.

Typo:
mixed-up placeholder text for private and public key

Suggestion:
dark mode support
```
<link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-dark.min.css" rel="stylesheet">
```

turn off browser spell check
```

<body spellcheck="false">
```

missing html title
```
<title>Age tool</title>
```

**Comment by MarinX** [comment]
Hey @kernelschmelze , thank you for the comment.

This is the initial idea and release but my plan is to make it more mobile-friendly (use a framework?), encrypt/decrypt files, and add encrypt/decrypt with a password.

When I find some free time, I will work on that.

**Comment by MarinX** [comment]
hey @kernelschmelze , thanks for the suggestions!
I added those changes so we can close this issue. A new release is generated v1.1.0
