### ISSUE TITLE
Support binary data?

### ISSUE THREAD

**Issue by neezer** [MarinX/agewasm#2]
First off, thanks for compiling this and making it available! Was having difficulty figuring out how to compile Age to WASM myself and this has saved me loads of time.

---

I'm building a tool based off of the WASM provided here and have need to encrypt binary data (pictures, movies, etc.). I've got it working by base64-encoding the files first before encrypting/decrypting with agewasm, but that balloons the file size. What I'd love is to be able to pass a [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) directly to `encrypt`/`decrypt` instead of a base64-encoded string.

Think that would be possible?

**Comment by MarinX** [comment]
It should be possible.
Looking at the docs, there is [CopyBytesToGo](https://pkg.go.dev/syscall/js#CopyBytesToGo) and [CopyBytesToJS](https://pkg.go.dev/syscall/js#CopyBytesToJS) which is exactly what you need!

Let me work on this and update this issue once it's released and tagged.
I will keep you posted,

**Comment by neezer** [comment]
@MarinX I got impatient and muddled my way through these modifications myself. Here's a gist with my modified files: https://gist.github.com/neezer/c366a4bde001577696d471dd33447a45

I'm guessing you won't use those modifications directly—hence the lack of a PR—because I went the binary data _**only**_ route and removed support for ASCII Armor (I don't need it in my app), but hopefully they're still helpful as reference.

**Comment by MarinX** [comment]
Hi @neezer , this is now done. Checkout the new release or visit the demo page to test it out :)
